const xAxis = g => g
  .attr(`transform`, `translate(0, ${aHeight - margin.bottom})`)
  .call(d3
    .axisBottom(x)
    .tickSizeOuter(0)
    .tickValues([0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
    .tickFormat(d => `${d}%`)
  )
  .call(g => g.append('text')
    .attr('x', aWidth - margin.right)
    .attr('y', -4)
    .attr('fill', '#000')
    .attr('text-anchor', 'end')
    .text(xAxisLabel)
  )